---
- hosts: servalab-machines
  become: true
  tasks:
    - name: Create user named sarvalabs
      ansible.builtin.user:
      name: sarvalabs
      group: sudo
      append: yes
      state: present

    - name: Download and install requir
      apt:
        name: "{{item}}"
        update_cache: yes
        state: present
      loop: 
        - prometheus-node-exporter
        - prometheus
        - grafana
    
    - name: Start and enable Services
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - prometheus-node-exporter
        - prometheus
        - grafana 


    

    
